create table "public"."data" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "topic_id" bigint not null,
    "question" character varying not null,
    "answer" character varying not null,
    "hint" character varying,
    "notes" character varying,
    "user_id" uuid
);


alter table "public"."data" enable row level security;

create table "public"."language" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "title" text not null,
    "description" text not null,
    "user_id" text
);


alter table "public"."language" enable row level security;

create table "public"."topic" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "language_id" bigint not null,
    "title" text not null,
    "description" text not null,
    "user_id" uuid
);


alter table "public"."topic" enable row level security;

CREATE UNIQUE INDEX data_pkey ON public.data USING btree (id);

CREATE UNIQUE INDEX language_pkey ON public.language USING btree (id);

CREATE UNIQUE INDEX topic_pkey ON public.topic USING btree (id);

alter table "public"."data" add constraint "data_pkey" PRIMARY KEY using index "data_pkey";

alter table "public"."language" add constraint "language_pkey" PRIMARY KEY using index "language_pkey";

alter table "public"."topic" add constraint "topic_pkey" PRIMARY KEY using index "topic_pkey";

alter table "public"."data" add constraint "public_data_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES topic(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."data" validate constraint "public_data_topic_id_fkey";

alter table "public"."data" add constraint "public_data_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."data" validate constraint "public_data_user_id_fkey";

alter table "public"."topic" add constraint "public_topic_language_id_fkey" FOREIGN KEY (language_id) REFERENCES language(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."topic" validate constraint "public_topic_language_id_fkey";

create or replace view "public"."random_data" as  SELECT d.id,
    d.created_at,
    d.question,
    d.answer,
    d.hint,
    d.user_id,
    d.topic_id,
    a.language_id
   FROM (data d
     JOIN ( SELECT t.id AS topic_id_main,
            t.language_id
           FROM (topic t
             JOIN language l ON ((t.language_id = l.id)))) a ON ((a.topic_id_main = d.topic_id)))
  ORDER BY (random());


grant delete on table "public"."data" to "anon";

grant insert on table "public"."data" to "anon";

grant references on table "public"."data" to "anon";

grant select on table "public"."data" to "anon";

grant trigger on table "public"."data" to "anon";

grant truncate on table "public"."data" to "anon";

grant update on table "public"."data" to "anon";

grant delete on table "public"."data" to "authenticated";

grant insert on table "public"."data" to "authenticated";

grant references on table "public"."data" to "authenticated";

grant select on table "public"."data" to "authenticated";

grant trigger on table "public"."data" to "authenticated";

grant truncate on table "public"."data" to "authenticated";

grant update on table "public"."data" to "authenticated";

grant delete on table "public"."data" to "service_role";

grant insert on table "public"."data" to "service_role";

grant references on table "public"."data" to "service_role";

grant select on table "public"."data" to "service_role";

grant trigger on table "public"."data" to "service_role";

grant truncate on table "public"."data" to "service_role";

grant update on table "public"."data" to "service_role";

grant delete on table "public"."language" to "anon";

grant insert on table "public"."language" to "anon";

grant references on table "public"."language" to "anon";

grant select on table "public"."language" to "anon";

grant trigger on table "public"."language" to "anon";

grant truncate on table "public"."language" to "anon";

grant update on table "public"."language" to "anon";

grant delete on table "public"."language" to "authenticated";

grant insert on table "public"."language" to "authenticated";

grant references on table "public"."language" to "authenticated";

grant select on table "public"."language" to "authenticated";

grant trigger on table "public"."language" to "authenticated";

grant truncate on table "public"."language" to "authenticated";

grant update on table "public"."language" to "authenticated";

grant delete on table "public"."language" to "service_role";

grant insert on table "public"."language" to "service_role";

grant references on table "public"."language" to "service_role";

grant select on table "public"."language" to "service_role";

grant trigger on table "public"."language" to "service_role";

grant truncate on table "public"."language" to "service_role";

grant update on table "public"."language" to "service_role";

grant delete on table "public"."topic" to "anon";

grant insert on table "public"."topic" to "anon";

grant references on table "public"."topic" to "anon";

grant select on table "public"."topic" to "anon";

grant trigger on table "public"."topic" to "anon";

grant truncate on table "public"."topic" to "anon";

grant update on table "public"."topic" to "anon";

grant delete on table "public"."topic" to "authenticated";

grant insert on table "public"."topic" to "authenticated";

grant references on table "public"."topic" to "authenticated";

grant select on table "public"."topic" to "authenticated";

grant trigger on table "public"."topic" to "authenticated";

grant truncate on table "public"."topic" to "authenticated";

grant update on table "public"."topic" to "authenticated";

grant delete on table "public"."topic" to "service_role";

grant insert on table "public"."topic" to "service_role";

grant references on table "public"."topic" to "service_role";

grant select on table "public"."topic" to "service_role";

grant trigger on table "public"."topic" to "service_role";

grant truncate on table "public"."topic" to "service_role";

grant update on table "public"."topic" to "service_role";

create policy "Enable read access for all users"
on "public"."data"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."language"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."topic"
as permissive
for select
to public
using (true);



